create or replace procedure "PROC_PROMUEVE_ASCENSO"
(iddepartamento IN NUMBER)
is
S_MANAGER NUMBER(5);
begin

SELECT EMPLOYEE_ID INTO S_MANAGER FROM EMPLOYEES WHERE DEPARTMENT_ID=iddepartamento AND ROWNUM = 1 ORDER BY HIRE_DATE; 

UPDATE DEPARTMENTS
SET MANAGER_ID = S_MANAGER
WHERE DEPARTMENT_ID=iddepartamento;

end;
