create or replace function "F_DESPLEGARPAIS"
(idempleado in NUMBER)
return VARCHAR2 is
s_country VARCHAR2(100);
begin
   select C.COUNTRY_NAME INTO s_country
   from EMPLOYEES E INNER JOIN DEPARTMENTS D ON D.DEPARTMENT_ID=E.DEPARTMENT_id
   INNER JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID
   INNER JOIN COUNTRIES C ON L.COUNTRY_ID=C.COUNTRY_ID
WHERE EMPLOYEE_ID=idempleado;
RETURN s_COUNTRY;
end;




